source "https://rubygems.org"
ruby RUBY_VERSION

# Default- and GitHub theme.
gem "minima", "~> 2.0"
gem "github-pages", group: :jekyll_plugins
gem "jekyll-whiteglass"

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.6"
  gem 'jekyll-livereload'
end
